number1 = float(input("Enter a first number: "))
number2 = float(input("Enter second number: "))
print(number1 == number2)
print(number1 != number2)
print(number1 > number2)
print(number1 < number2)
print(number1 >= number2)
print(number1 <= number2)